name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME }}
        STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
        FIRST_NAME: ${{ secrets.FIRST_NAME }}
        LAST_NAME: ${{ secrets.LAST_NAME }}
        GLITCH_USER: ${{ secrets.GLITCH_USER }}
        INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
        INVALID_USER: ${{ secrets.INVALID_USER }}
        LOCKED_OUT_USERNAME: ${{ secrets.LOCKED_OUT_USERNAME }}
        POSTAL_CODE: ${{ secrets.POSTAL_CODE }}
        PROBLEM_USER: ${{ secrets.PROBLEM_USER }}

      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
